version: "3.3"

networks:
  test:
    driver: bridge


services:
  db:
    networks:
      - test
    env_file:
      - .env
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../bot-db/postgres_data:/var/lib/postgresql/data


  app:
    networks:
      - test
    build: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./alembic:/telegram-bot-mmo/alembic
